version: '3.6'

services:

  proxy:
    image: nginx:1.15.8-alpine
    container_name: nginx.cityvizor.cesko.digital
    ports:
      - "4200:80"
    volumes:
      - ./nginx:/etc/nginx:ro
    environment:
      NGINX_HOST: cityvizor.cesko.digital
      NGINX_PORT: 80

  backend-kotlin:
    image: backend-kotlin
    build: server-kotlin/.
    container_name: backend.cityvizor.cesko.digital
    environment:
      DATABASE_ADDRESS: db.cityvizor.cesko.digital
    depends_on:
      - postgres
      - proxy

  cityvizor-server:
    image: cityvizor-server
    build: ./server
    command: node dist/server.js
    container_name: server.cityvizor.cesko.digital
    environment:
      NODE_ENV: local
    volumes:
      - ./data:/user/src/app/data
    depends_on: 
      - postgres
      - proxy

  cityvizor-worker:
    image: cityvizor-server
    build: ./server
    command: node dist/worker.js
    container_name: worker.cityvizor.cesko.digital
    environment:
      NODE_ENV: local
    volumes:
      - ./data:/user/src/app/data
    depends_on: 
      - postgres

  cityvizor-client:
    image: cityvizor-client
    build: ./client   
    container_name: client.cityvizor.cesko.digital
    environment:
      NODE_ENV: local  
    depends_on: 
      - proxy  
      
  postgres:
    image: postgres:11.1
    container_name: db.cityvizor.cesko.digital
    environment:
      POSTGRES_DB: cityvizor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - ./database/oict_dump.sql:/docker-entrypoint-initdb.d/oict_dump.sql
    ports:
      - 5432:5432
